#!/usr/bin/env python3
"""OpenSlide on a CAMELYON16 whole-slide image, checked against the publisher's own artifacts.

Nothing here is a band on an observed value. The ladder, strongest last:

  1. the publisher's md5 for all three objects, read from its own checksums.md5 (963 entries)
  2. WSI and mask are pixel-aligned -- identical dimensions and level structure. This is the
     precondition that makes every spatial comparison below mean anything, so it is asserted
     rather than assumed. (Measured by probe: both are 61440x53760 with 8 levels.)
  3. pyramid arithmetic -- level_downsamples are exactly 2**k and each level's dimensions
     follow from level 0. Exact, no tolerance.
  4. a read-overlap invariance -- two overlapping read_region calls must agree BIT-EXACTLY in
     their overlap. No reference needed; a broken tile stitcher cannot satisfy it.
  5. the mask's label set is exactly {0,1,2}, which is what the publisher's README documents
     (1 = normal tissue, 2 = tumour). Any other value means the read is wrong.
  6. the annotation polygons against the shipped mask. The README states the tumour regions
     were "generated by converting the annotation polygons to pixel masks", so rasterising
     them reproduces the publisher's own derived artifact from its own source. Asserted on
     INTERIORS (eroded by BOUNDARY_PX) because rasterisation edge convention is the only
     legitimate source of disagreement -- the claim meant is "the interiors agree", not a
     convenient IoU proxy.
  7. the Exclusion polygon as a built-in NEGATIVE CONTROL. The README says Exclusion regions
     are non-tumour areas cut out of the Tumor group, and this slide's Exclusion polygon lies
     INSIDE one of its Tumor polygons. So its interior must NOT be labelled tumour even though
     it is inside a tumour annotation. That is what stops check 6 passing vacuously.
  8. the macro/micro/ITC class in the organizers' reference.csv, against the challenge's own
     published size thresholds, measured from the mask through openslide's mpp.

Run with `python3 -u`.
"""
import os
import resource
import subprocess
import sys
import xml.etree.ElementTree as ET

import numpy as np
import openslide
import scipy.ndimage as ndi
import skimage
from skimage.draw import polygon as draw_polygon
from skimage.measure import label as cc_label
from skimage.measure import regionprops
from skimage.morphology import disk, erosion

WSI = "/tmp/tumor_091.tif"
MASK = "/tmp/tumor_091_mask.tif"
XML = "/tmp/tumor_091.xml"
SLIDE = "tumor_091"

LEVEL = 4            # 3840x3360 -- whole mask fits comfortably; mpp here is 16x level 0
BOUNDARY_PX = 2      # at level 4 this is 32 level-0 pixels, ~7 um: generous for an edge convention
# CAMELYON16's published slide-level classes, by the largest metastasis' longest diameter.
MACRO_MM = 2.0       # > 2.0 mm
DILATION_UM = 75.0   # theirs: "approximately 5 tumor cells", from evaluate.py
ITC_MM = 0.2         # < 0.2 mm is an isolated tumour cell cluster; between the two is "micro"

out = {}


def rec(k, v):
    out[k] = v
    print("%s\t%s" % (k, v))


def die(msg):
    dump()
    sys.exit("FAIL: %s" % msg)


def dump():
    with open("/tmp/score.tsv", "w") as fh:
        fh.write("observable\tvalue\n")
        for k, v in out.items():
            fh.write("%s\t%s\n" % (k, v))


rec("openslide_python", getattr(openslide, "__version__", "unknown"))
rec("openslide_library", openslide.__library_version__)
rec("numpy", np.__version__)
rec("scikit_image", skimage.__version__)

# ---- 1. the publisher's own checksums ----------------------------------------------------
for name, path in (("images/%s.tif" % SLIDE, WSI),
                   ("masks/%s_mask.tif" % SLIDE, MASK),
                   ("annotations/%s.xml" % SLIDE, XML)):
    want = None
    for line in open("/tmp/checksums.md5", errors="replace"):
        parts = line.split()
        if len(parts) == 2 and parts[1].lstrip("*") == name:
            want = parts[0]
            break
    if want is None:
        die("%s has no line in the publisher's checksums.md5" % name)
    got = subprocess.run(["md5sum", path], capture_output=True, text=True).stdout.split()[0]
    if got != want:
        die("%s md5 %s != publisher %s" % (name, got, want))
rec("identity_publisher_md5", "3 of 3 match the publisher's checksums.md5")

wsi = openslide.OpenSlide(WSI)
mask = openslide.OpenSlide(MASK)

# ---- 2. pixel alignment: the precondition for everything spatial -------------------------
rec("wsi_dimensions", wsi.dimensions)
rec("mask_dimensions", mask.dimensions)
if wsi.dimensions != mask.dimensions:
    die("WSI %s and mask %s differ in size -- no spatial comparison is valid"
        % (wsi.dimensions, mask.dimensions))
if wsi.level_dimensions != mask.level_dimensions:
    die("WSI and mask pyramids differ: %s vs %s" % (wsi.level_dimensions, mask.level_dimensions))
mpp0 = float(wsi.properties["openslide.mpp-x"])
mpp_mask = float(mask.properties["openslide.mpp-x"])
rec("mpp_level0_um", "%.9f" % mpp0)
rel = abs(mpp0 - mpp_mask) / mpp0
rec("wsi_vs_mask_mpp_relative", "%.3e" % rel)
if rel > 1e-4:
    die("WSI and mask disagree on mpp by %.3e" % rel)
rec("identity_pixel_aligned",
    "WSI and mask identical at all %d levels, mpp agrees to %.1e" % (wsi.level_count, rel))

# ---- 3. pyramid arithmetic, exact --------------------------------------------------------
w0, h0 = wsi.dimensions
bad = []
for k, (ds, (w, h)) in enumerate(zip(wsi.level_downsamples, wsi.level_dimensions)):
    if abs(ds - 2 ** k) > 1e-9:
        bad.append("level %d downsample %.6f != %d" % (k, ds, 2 ** k))
    if abs(w - w0 / 2 ** k) > 1 or abs(h - h0 / 2 ** k) > 1:
        bad.append("level %d dims %s inconsistent with level 0 %s" % (k, (w, h), (w0, h0)))
rec("level_downsamples", tuple(round(d, 6) for d in wsi.level_downsamples))
if bad:
    die("pyramid arithmetic: %s" % bad[0])
rec("identity_pyramid", "all %d levels are exact powers of two from level 0" % wsi.level_count)

# ---- 4. read-overlap invariance, bit-exact ----------------------------------------------
# Two reads whose regions overlap must return identical bytes in the overlap. Reading at a
# level means stitching tiles, and a stitcher that mis-handles tile edges fails this while
# still producing a plausible-looking image.
L = 2
a = np.asarray(wsi.read_region((4096, 4096), L, (512, 512)).convert("RGB"))
b = np.asarray(wsi.read_region((4096 + 256 * 2 ** L, 4096), L, (512, 512)).convert("RGB"))
ov_a, ov_b = a[:, 256:, :], b[:, :256, :]
diff = int(np.abs(ov_a.astype(np.int32) - ov_b.astype(np.int32)).max())
rec("read_overlap_max_abs_diff", diff)
if diff != 0:
    die("overlapping reads differ by %d -- tile stitching is wrong" % diff)
rec("identity_read_overlap", "256x512 overlap byte-identical across two reads (level %d)" % L)

# ---- 5. the mask's label set ------------------------------------------------------------
lw, lh = mask.level_dimensions[LEVEL]
m = np.asarray(mask.read_region((0, 0), LEVEL, (lw, lh)).convert("L"))
vals, counts = np.unique(m, return_counts=True)
rec("working_level", "%d, shape %s, mpp %.6f um" % (LEVEL, m.shape, mpp0 * 2 ** LEVEL))
rec("mask_value_histogram", dict(zip(vals.tolist(), counts.tolist())))
if not set(vals.tolist()) <= {0, 1, 2}:
    die("mask carries values outside {0,1,2}: %s -- the pyramid may be interpolating"
        % vals.tolist())
rec("identity_mask_labels", "exactly the documented {0,1,2} (0 bg, 1 normal, 2 tumour)")

# ---- 6/7. the annotation polygons, and the Exclusion negative control -------------------
root = ET.parse(XML).getroot()
tumour = np.zeros(m.shape, bool)
exclusion = np.zeros(m.shape, bool)
ngroups = {"Tumor": 0, "Exclusion": 0, "other": 0}
scale = 1.0 / 2 ** LEVEL
for ann in root.findall(".//Annotation"):
    co = [(float(c.get("X")) * scale, float(c.get("Y")) * scale)
          for c in ann.findall(".//Coordinate")]
    if len(co) < 3:
        continue
    rr, cc = draw_polygon(np.array([p[1] for p in co]), np.array([p[0] for p in co]),
                          shape=m.shape)
    grp = ann.get("PartOfGroup")
    if grp == "Tumor":
        tumour[rr, cc] = True
        ngroups["Tumor"] += 1
    elif grp == "Exclusion":
        exclusion[rr, cc] = True
        ngroups["Exclusion"] += 1
    else:
        ngroups["other"] += 1
rec("xml_annotation_groups", ngroups)
if ngroups["Tumor"] == 0:
    die("no Tumor annotations rasterised -- the comparison would be vacuous")

truth = tumour & ~exclusion
is_tumour = (m == 2)
inter = int((truth & is_tumour).sum())
dice = 2.0 * inter / max(1, int(truth.sum()) + int(is_tumour.sum()))
iou = inter / max(1, int((truth | is_tumour).sum()))
rec("polygon_vs_mask_dice", "%.6f" % dice)
rec("polygon_vs_mask_iou", "%.6f" % iou)

se = disk(BOUNDARY_PX)
truth_in = erosion(truth, se)
outside_in = erosion(~(tumour | exclusion), se)
miss_in = int((truth_in & ~is_tumour).sum())
miss_out = int((outside_in & is_tumour).sum())
rec("interior_px_inside_polygons", int(truth_in.sum()))
rec("interior_px_not_labelled_tumour", miss_in)
rec("exterior_px_labelled_tumour", miss_out)
if truth_in.sum() == 0:
    die("no interior pixels survived erosion -- the check would be vacuous")
if miss_in or miss_out:
    die("polygon interiors disagree with the mask: %d inside unlabelled, %d outside labelled"
        % (miss_in, miss_out))
rec("identity_polygons_vs_mask",
    "all %d interior pixels agree, both directions, eroded %d px (%.1f um)"
    % (int(truth_in.sum()), BOUNDARY_PX, BOUNDARY_PX * mpp0 * 2 ** LEVEL))

# The negative control. This slide's Exclusion polygon sits inside a Tumor polygon, so a
# rasterisation that ignored Exclusion would still pass check 6 in the other direction.
excl_in = erosion(exclusion & tumour, se)
rec("exclusion_interior_px", int(excl_in.sum()))
if excl_in.sum() == 0:
    die("Exclusion polygon does not lie inside a Tumor polygon here -- no negative control")
excl_labelled = int((excl_in & is_tumour).sum())
rec("exclusion_interior_labelled_tumour", excl_labelled)
if excl_labelled:
    die("%d px inside the Exclusion region are labelled tumour" % excl_labelled)
rec("identity_exclusion_control",
    "%d px inside a Tumor polygon but inside Exclusion are correctly NOT tumour"
    % int(excl_in.sum()))

# ---- 8. the organizers' slide class, against the challenge's published thresholds -------
ref = None
for line in open("/tmp/reference.csv"):
    if line.startswith(SLIDE + "."):
        ref = [x.strip() for x in line.strip().split(",")]
rec("reference_csv_row", ref)
if not ref:
    die("%s absent from the organizers' reference.csv" % SLIDE)
ref_type, ref_class = ref[1], ref[2]
if (ref_type == "tumor") != bool(is_tumour.any()):
    die("reference.csv says type=%s but mask tumour presence is %s"
        % (ref_type, bool(is_tumour.any())))
rec("identity_reference_type", "reference.csv type=%s agrees with the mask" % ref_type)

# The organizers' OWN evaluation-mask procedure, from evaluation/evaluate.py's
# compute_evaluation_mask(). Reimplemented rather than invented, because a first version of
# this check labelled connected components directly and got `micro` against a reference of
# `macro` -- the difference is entirely step 3 below, which I had read in their docstring and
# then left out. Two details nothing but their source would have told me:
#
#   * the dilation threshold is dilation_distance / (spacing * 2.0) -- the factor of 2 is theirs
#   * the size thresholds have the dilation distance ADDED BACK (`(200.0 + dilation_distance)`),
#     which is how they compensate for having just grown every region
#
# and they use major_axis_length, not a Feret diameter. Using their metric is what makes this a
# comparison against their label rather than against a quantity of my own.
mpp_l = mpp0 * 2 ** LEVEL
neg = (m != 2)
dist = ndi.distance_transform_edt(neg)
thr_px = DILATION_UM / (mpp_l * 2.0)
dilated = dist < thr_px
filled = ndi.binary_fill_holes(dilated)
evalmask = cc_label(filled, connectivity=2)
props = regionprops(evalmask)
rec("dilation_threshold_px", "%.4f  (%.1f um at %.6f um/px)" % (thr_px, DILATION_UM, mpp_l))
rec("lesions_before_dilation", int(cc_label(is_tumour).max()))
rec("lesions_after_dilation", len(props))

major_px = sorted((p.axis_major_length for p in props), reverse=True)
feret_px = sorted((p.feret_diameter_max for p in props), reverse=True)
itc_thr_px = (ITC_MM * 1000.0 + DILATION_UM) / mpp_l
macro_thr_px = (MACRO_MM * 1000.0 + DILATION_UM) / mpp_l
rec("major_axis_mm", [round(v * mpp_l / 1000.0, 4) for v in major_px[:6]])
largest_px = major_px[0] if major_px else 0.0
rec("largest_major_axis_mm", "%.4f" % (largest_px * mpp_l / 1000.0))
rec("largest_feret_mm", "%.4f" % ((feret_px[0] if feret_px else 0.0) * mpp_l / 1000.0))
rec("macro_threshold_mm", "%.4f" % (macro_thr_px * mpp_l / 1000.0))
implied = ("macro" if largest_px > macro_thr_px
           else ("itc" if largest_px < itc_thr_px else "micro"))
rec("implied_class", implied)
rec("reference_class", ref_class)
rec("class_agrees", implied == ref_class)

# ------------------------------------------------------------------------------------------
# REPORTED, NOT ASSERTED -- and measured across nine slides before deciding that.
#
# An earlier version asserted that the organizers' procedure reproduces their reference.csv
# class. It does not, and one slide disagreeing proved nothing, so the question was settled by
# running the same procedure over 4 macro + 4 micro + this slide:
#
#   micro reference -> implied micro, 4 of 4.  No micro slide ever measures as macro.
#   macro reference -> implied macro for tumor_009 (8.04 mm) and tumor_011 (3.73 mm),
#                      but micro for tumor_004 (1.97), tumor_010 (0.38) and tumor_091 (1.41).
#
# Two of those three are explicable: tumor_010 is on the publisher's own list of
# non-exhaustively annotated slides, and tumor_004's FERET diameter (2.1555 mm) clears the
# 2.075 mm threshold its major axis misses. tumor_091 is not explicable -- 1.47 mm by either
# metric, exhaustively annotated.
#
# The failure being ONE-SIDED is the informative part: the class is the pathologists'
# measurement of the original specimen, while the mask is a derived annotation that can
# under-represent extent. So asserting the class from the mask compares a clinical label
# against a geometric proxy for it -- a method difference, not a correctness check. The ITC
# branch is untestable here for a separate reason: reference.csv contains no itc slides at
# all (239 negative, 80 micro, 80 macro), so an "exceeds the ITC threshold" assertion would
# have been vacuous rather than wrong.
# ------------------------------------------------------------------------------------------
rec("identity_slide_class", "NOT ASSERTED -- see the cross-slide measurement; the class is "
    "clinical metadata the mask does not determine")


rec("peak_rss_mib", "%.1f" % (resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024.0))
df = subprocess.run(["df", "-m", "/tmp"], capture_output=True, text=True).stdout.splitlines()
rec("tmp_filesystem", " ".join(df[-1].split()) if len(df) > 1 else "?")
wsi.close()
mask.close()
dump()
print("PATHOLOGY OK")
