#!/usr/bin/env python3
"""Generate catalog/recipes.md from the recipes themselves — frontmatter, lede, and the
input-dependency each recipe actually has. The inventory is derived, never hand-maintained,
so it can't drift from what ships (the reviewer's item 2).

The Inputs column is the dependency visibility item 4 wants, inferred today from stage
scripts + spec inputs. When a recipe grows an explicit `depends_on:` frontmatter list,
that overrides the inference — item 4 slots in here without a rewrite.

    python3 scripts/gen_catalog.py            # write catalog/recipes.md
    python3 scripts/gen_catalog.py --check     # exit 1 if the committed file is stale
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "catalog", "recipes.md")
BANNER = "<!-- GENERATED by scripts/gen_catalog.py — do not edit by hand; run `make catalog`. -->"


def frontmatter(text):
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    fm = {}
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip()
    return fm


def lede(text):
    """First prose line after the H1 — the recipe's own one-liner."""
    body = re.sub(r"^---\n.*?\n---\n", "", text, flags=re.S)
    lines = body.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("# "):
            for nxt in lines[i + 1:]:
                if nxt.strip() and not nxt.startswith(("#", ">", "```")):
                    return nxt.strip()
    return ""


def stage_builds(recipe_dir):
    """Which inputs/<prefix>/ this recipe's stage script uploads to."""
    sh = os.path.join(recipe_dir, "stage-inputs.sh")
    if not os.path.exists(sh):
        return set()
    text = open(sh, encoding="utf-8").read()
    # same regex as check_pages.py's staging-coverage: catches both inputs/<p>/ upload
    # paths and PREFIX="inputs/<p>" variable forms (no trailing slash).
    return {m.group(1) for m in re.finditer(r"inputs/([\w.-]+)", text)}


def spec_inputs(recipe_dir):
    """(input prefixes read from inputs/<p>/, sibling recipes read from runs/<x>/)."""
    prefixes, runs = set(), set()
    for spec in glob.glob(os.path.join(recipe_dir, "*.task.json")):
        text = open(spec, encoding="utf-8").read()
        prefixes |= {m.group(1) for m in re.finditer(r'"source":\s*"s3://[^/]+/inputs/([\w.-]+)/', text)}
        runs |= {m.group(1) for m in re.finditer(r'"source":\s*"s3://[^/]+/runs/([\w.-]+)/', text)}
    return prefixes, runs


def main():
    recipes = {}  # name -> dir
    for readme in glob.glob(os.path.join(ROOT, "recipes", "*", "README.md")):
        d = os.path.dirname(readme)
        recipes[os.path.basename(d)] = d

    # prefix -> recipe whose stage script builds it
    builder = {}
    for name, d in recipes.items():
        for p in stage_builds(d):
            builder[p] = name

    rows = []
    for name in sorted(recipes):
        d = recipes[name]
        text = open(os.path.join(d, "README.md"), encoding="utf-8").read()
        fm = frontmatter(text)
        env = fm.get("env") or ("pipeline" if "images" in fm else "aarchbio")
        domain = env
        prefixes, runs = spec_inputs(d)
        has_own_stage = os.path.exists(os.path.join(d, "stage-inputs.sh"))

        # deps: siblings this recipe needs staged/run first
        deps = set(x for x in runs if x != name)
        for p in prefixes:
            b = builder.get(p)
            if b and b != name:
                deps.add(b)

        # explicit depends_on frontmatter (item 4) overrides the inference
        if fm.get("depends_on"):
            deps = {x.strip() for x in re.split(r"[,\[\]\s]+", fm["depends_on"]) if x.strip()}

        if deps:
            inputs = "reuse: " + ", ".join(sorted(deps))
        elif has_own_stage:
            inputs = "stage"
        elif not prefixes and not runs:
            inputs = "build-in-task"
        else:
            inputs = "stage"  # reads a prefix its own stage builds
        rows.append((domain, name, lede(text), env, inputs))

    # group by domain, alphabetical within
    domains = sorted({r[0] for r in rows})
    out = [BANNER, "", "# The recipe catalog", "",
           f"Every recipe here runs one tool on a Graviton4 box, verified, self-terminating "
           f"— **{len(rows)} working examples**, generated from the recipes themselves so this "
           f"list is always what actually ships. Each links to its page; run any with "
           f"`make run RECIPE=<name>`.", "",
           "**Inputs** — what a clean-account reader does first: **build-in-task** (nothing to "
           "stage), **stage** (`make stage RECIPE=<name>`), or **reuse: X** (stage/run recipe X "
           "first — its output is this recipe's input).", ""]
    for dom in domains:
        drows = [r for r in rows if r[0] == dom]
        out.append(f"## {dom}")
        out.append("")
        out.append("| Recipe | What it does | Env | Inputs |")
        out.append("|---|---|---|---|")
        for _, name, desc, env, inputs in drows:
            out.append(f"| [{name}](../recipes/{name}/README.md) | {desc} | {env} | {inputs} |")
        out.append("")
    content = "\n".join(out).rstrip() + "\n"

    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != content:
            print("catalog/recipes.md is stale — run `make catalog`", file=sys.stderr)
            return 1
        print("catalog/recipes.md up to date")
        return 0
    open(OUT, "w", encoding="utf-8").write(content)
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(rows)} recipes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
