#!/usr/bin/env python3
"""Generate catalog/recipes.md from the recipes themselves — frontmatter, lede, and the
input-dependency each recipe actually has. The inventory is derived, never hand-maintained,
so it can't drift from what ships (the reviewer's item 2).

The Inputs column is the dependency visibility item 4 wants, inferred today from stage
scripts + spec inputs. When a recipe grows an explicit `depends_on:` frontmatter list,
that overrides the inference — item 4 slots in here without a rewrite.

    python3 scripts/gen_catalog.py            # write catalog/recipes.md
    python3 scripts/gen_catalog.py --check     # exit 1 if the committed file is stale
"""
import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "catalog", "recipes.md")
BANNER = "<!-- GENERATED by scripts/gen_catalog.py — do not edit by hand; run `make catalog`. -->"


def frontmatter(text):
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    fm = {}
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip()
    return fm


def lede(text):
    """First prose line after the H1 — the recipe's own one-liner."""
    body = re.sub(r"^---\n.*?\n---\n", "", text, flags=re.S)
    lines = body.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("# "):
            for nxt in lines[i + 1:]:
                if nxt.strip() and not nxt.startswith(("#", ">", "```")):
                    return nxt.strip()
    return ""


CATALOG_DIR = os.path.join(ROOT, "catalog")


def retarget_links(text, recipe_dir):
    """Rewrite a lede's relative links so they resolve from catalog/recipes.md, not from the
    recipe dir the lede was written in: `../mafft/README.md` (correct from recipes/muscle/)
    becomes `../recipes/mafft/README.md`. Ledes are copied verbatim, so without this the one
    artifact nobody hand-edits is the one that carries broken links."""
    def repl(m):
        label, target = m.group(1), m.group(2)
        url = target.split()[0]
        if url.startswith(("http://", "https://", "mailto:", "#")):
            return m.group(0)
        path, _, anchor = url.partition("#")
        if not path:
            return m.group(0)
        newrel = os.path.relpath(os.path.normpath(os.path.join(recipe_dir, path)), CATALOG_DIR)
        return f"[{label}]({newrel}{'#' + anchor if anchor else ''})"
    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, text)


def stage_builds(recipe_dir):
    """Which inputs/<prefix>/ this recipe's stage script uploads to."""
    sh = os.path.join(recipe_dir, "stage-inputs.sh")
    if not os.path.exists(sh):
        return set()
    text = open(sh, encoding="utf-8").read()
    # Attribution needs UPLOAD DESTINATIONS, not any mention. The loose `inputs/<p>` match
    # (which check_pages.py still uses, correctly, to ask only "is this prefix buildable
    # at all") counted comments and echo strings: recipes/abundance says "they already live
    # under inputs/kraken2/ and this recipe reads them there", which made abundance a
    # "builder" of kraken2's prefix. So: drop comments, then require an s3:// destination
    # or a path-variable assignment.
    body = "\n".join(l.split("#", 1)[0] for l in text.splitlines())
    pats = (r"s3://[^/\s\"']*/inputs/([\w.-]+)",
            r"^\s*\w*(?:PREFIX|DST|DEST|TARGET)\w*=\"?[^\"\n]*?inputs/([\w.-]+)")
    found = set()
    for pat in pats:
        found |= {m.group(1) for m in re.finditer(pat, body, re.M)}
    return found


def git_updated(recipe_dir):
    """git commit date of the recipe's last substantive change — page freshness, derived
    not stored (git already knows). Normalized out of --check so it can't cause false stale."""
    try:
        out = subprocess.run(["git", "log", "-1", "--format=%cd", "--date=short", "--", recipe_dir],
                             cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        return out or "—"
    except Exception:
        return "—"


def spec_inputs(recipe_dir):
    """(input prefixes read from inputs/<p>/, sibling recipes read from runs/<x>/)."""
    prefixes, runs = set(), set()
    for spec in glob.glob(os.path.join(recipe_dir, "*.task.json")):
        text = open(spec, encoding="utf-8").read()
        prefixes |= {m.group(1) for m in re.finditer(r'"source":\s*"s3://[^/]+/inputs/([\w.-]+)/', text)}
        runs |= {m.group(1) for m in re.finditer(r'"source":\s*"s3://[^/]+/runs/([\w.-]+)/', text)}
    return prefixes, runs


def main():
    recipes = {}  # name -> dir
    for readme in glob.glob(os.path.join(ROOT, "recipes", "*", "README.md")):
        d = os.path.dirname(readme)
        recipes[os.path.basename(d)] = d

    # prefix -> EVERY recipe whose stage script uploads to it.
    #
    # This was `builder[p] = name`, last-writer-wins over a filesystem-ordered glob -- so a
    # prefix two recipes both stage (inputs/bwa-real/ is built partly by bwa-samtools and
    # partly by bwa-mem2) resolved differently on macOS and on Linux, and the generated
    # catalog was platform-dependent. `make catalog` locally then disagreed with CI's
    # --check forever. A set, emitted sorted, is both deterministic and the truthful answer:
    # when a prefix has two partial builders, name them both.
    builder = {}
    for name in sorted(recipes):
        for p in stage_builds(recipes[name]):
            builder.setdefault(p, set()).add(name)

    rows = []
    for name in sorted(recipes):
        d = recipes[name]
        text = open(os.path.join(d, "README.md"), encoding="utf-8").read()
        fm = frontmatter(text)
        env = fm.get("env") or ("pipeline" if "images" in fm else "aarchbio")
        domain = env
        prefixes, runs = spec_inputs(d)
        has_own_stage = os.path.exists(os.path.join(d, "stage-inputs.sh"))

        # Two dependency KINDS, because they mean different reader actions — the actionable
        # distinction item 4 exists for, not the mere fact of a dependency:
        #   stage-dep: reads a sibling's *staged input*  -> `make stage RECIPE=<sib>`
        #   run-dep:   reads a sibling's *run output*     -> `make run RECIPE=<sib>` and wait
        stage_deps = {r for p in prefixes for r in builder.get(p, ()) if r != name}
        run_deps = {x for x in runs if x != name}

        # Inference is the default; `depends_on` overrides only where it's wrong or can't see
        # the dependency (e.g. a pure ordering dep). Syntax: `depends_on: stage:bwa-samtools,
        # run:freebayes` — a bare token defaults to a stage-dep. Not required anywhere today.
        if fm.get("depends_on"):
            stage_deps, run_deps = set(), set()
            for tok in re.split(r"[,\s]+", fm["depends_on"]):
                kind, _, rec = tok.partition(":")
                if not (rec or kind):
                    continue
                (run_deps if (rec and kind == "run") else stage_deps).add(rec or kind)

        # A sibling needed as both a stage-dep and a run-dep collapses to the stronger action:
        # `make run RECIPE=X` already requires X staged, so listing both would be redundant
        # (the cross-validation recipes — bowtie2/diamond/kallisto — reuse a sibling both ways).
        stage_targets = (({name} if has_own_stage else set()) | stage_deps) - run_deps
        segs = []
        if stage_targets == {name}:
            segs.append("stage")                                    # `make stage RECIPE=<this>`
        elif stage_targets:
            segs.append("stage: " + ", ".join(sorted(stage_targets)))
        if run_deps:
            segs.append("run: " + ", ".join(sorted(run_deps)))
        inputs = " · ".join(segs) if segs else ("build-in-task" if not (prefixes or runs) else "stage")
        rows.append((domain, name, retarget_links(lede(text), d), env, inputs,
                     git_updated(os.path.relpath(d, ROOT)), fm.get("last_verified", "—")))

    # group by domain, alphabetical within
    domains = sorted({r[0] for r in rows})
    out = [BANNER, "", "# The recipe catalog", "",
           f"Every recipe here runs one tool on a Graviton4 box, verified, self-terminating "
           f"— **{len(rows)} working examples**, generated from the recipes themselves so this "
           f"list is always what actually ships. Each links to its page; run most with "
           f"`make run RECIPE=<name>` — a **pipeline** recipe (Env `pipeline`) launches through "
           f"its own workflow engine instead, as its page shows, not `make run`.", "",
           "**Inputs** — what a clean-account reader runs *before* `make run`, and the two kinds "
           "are different actions: **build-in-task** (nothing to stage) · **stage** "
           "(`make stage RECIPE=<this>`) · **stage: X** (`make stage RECIPE=X` — this recipe "
           "reuses X's staged input) · **run: X** (`make run RECIPE=X` and wait — this recipe "
           "reads X's run output).", "",
           "**Updated** is the git date of the page's last change (freshness). **Verified** is "
           "the date a real run last confirmed it — `—` means not verified since tracking began, "
           "an honest TODO for the next run, never backfilled.", ""]
    for dom in domains:
        drows = [r for r in rows if r[0] == dom]
        out.append(f"## {dom}")
        out.append("")
        out.append("| Recipe | What it does | Env | Inputs | Updated | Verified |")
        out.append("|---|---|---|---|---|---|")
        for _, name, desc, env, inputs, updated, verified in drows:
            out.append(f"| [{name}](../recipes/{name}/README.md) | {desc} | {env} | {inputs} | {updated} | {verified} |")
        out.append("")
    content = "\n".join(out).rstrip() + "\n"

    # Blank the git-derived Updated column before comparing: it advances on every commit that
    # touches a recipe, so gating on it would make the catalog perpetually "stale". Structure,
    # deps, and the hand-set Verified column are still gated.
    def norm(t):
        return re.sub(r"\| (?:\d{4}-\d{2}-\d{2}|—) (\| (?:\d{4}-\d{2}-\d{2}|—) \|)$",
                      r"| UPDATED \1", t, flags=re.M)

    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if norm(current) != norm(content):
            print("catalog/recipes.md is stale — run `make catalog`", file=sys.stderr)
            import difflib
            d = list(difflib.unified_diff(norm(current).splitlines(), norm(content).splitlines(),
                                          "committed", "regenerated", lineterm="", n=0))
            for line in d[:24]:
                print("  " + line, file=sys.stderr)
            if len(d) > 24:
                print(f"  … {len(d) - 24} more diff lines", file=sys.stderr)
            return 1
        print("catalog/recipes.md up to date")
        return 0
    open(OUT, "w", encoding="utf-8").write(content)
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(rows)} recipes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
